package views;

import org.apache.axis2.AxisFault;

import servicelayer.service.ServiceWebStub;
import servicelayer.service.ServiceWebStub.GetUser;
import servicelayer.service.ServiceWebStub.VOUser;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;

public class SearchUserDescription extends CustomComponent implements View, Button.ClickListener{

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button btnSearch;
	@AutoGenerated
	private TextField txtEmail;
	@AutoGenerated
	private TextField txtAddress;
	@AutoGenerated
	private TextField txtSurname;
	@AutoGenerated
	private TextField txtName;
	@AutoGenerated
	private TextField txtId;
	@AutoGenerated
	private Label lblEmail;
	@AutoGenerated
	private Label lblAddress;
	@AutoGenerated
	private Label lblSurname;
	@AutoGenerated
	private Label lblName;
	@AutoGenerated
	private Label lblId;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public SearchUserDescription() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		btnSearch.addClickListener(new Button.ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				ServiceWebStub userDescriptionService;
				try {
					userDescriptionService = new ServiceWebStub();
					
					GetUser getUserDescription = new GetUser();
					getUserDescription.setId(Integer.parseInt(txtId.getValue()));
					VOUser userDesc = userDescriptionService.getUser(getUserDescription).get_return();
					
					txtId.setValue(String.valueOf(userDesc.getId()));
					txtName.setValue(userDesc.getName());
					txtSurname.setValue(userDesc.getLastName());				
					txtEmail.setValue(userDesc.getEmail());
					
				}catch (AxisFault e) {
					e.printStackTrace();
				} catch (java.rmi.RemoteException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("420px");
		mainLayout.setHeight("260px");
		
		// top-level component properties
		setWidth("420px");
		setHeight("260px");
		
		// lblId
		lblId = new Label();
		lblId.setImmediate(false);
		lblId.setWidth("-1px");
		lblId.setHeight("-1px");
		lblId.setValue("Id");
		mainLayout.addComponent(lblId, "top:20.0px;left:40.0px;");
		
		// lblName
		lblName = new Label();
		lblName.setImmediate(false);
		lblName.setWidth("-1px");
		lblName.setHeight("-1px");
		lblName.setValue("Nombre");
		mainLayout.addComponent(lblName, "top:60.0px;left:40.0px;");
		
		// lblSurname
		lblSurname = new Label();
		lblSurname.setImmediate(false);
		lblSurname.setWidth("-1px");
		lblSurname.setHeight("-1px");
		lblSurname.setValue("Apellido");
		mainLayout.addComponent(lblSurname, "top:102.0px;left:40.0px;");
		
		// lblAddress
		lblAddress = new Label();
		lblAddress.setImmediate(false);
		lblAddress.setWidth("-1px");
		lblAddress.setHeight("-1px");
		lblAddress.setValue("Direccion");
		mainLayout.addComponent(lblAddress, "top:140.0px;left:40.0px;");
		
		// lblEmail
		lblEmail = new Label();
		lblEmail.setImmediate(false);
		lblEmail.setWidth("-1px");
		lblEmail.setHeight("-1px");
		lblEmail.setValue("Correo");
		mainLayout.addComponent(lblEmail, "top:180.0px;left:40.0px;");
		
		// txtId
		txtId = new TextField();
		txtId.setImmediate(false);
		txtId.setWidth("-1px");
		txtId.setHeight("-1px");
		mainLayout.addComponent(txtId, "top:20.0px;left:120.0px;");
		
		// txtName
		txtName = new TextField();
		txtName.setImmediate(false);
		txtName.setWidth("-1px");
		txtName.setHeight("-1px");
		mainLayout.addComponent(txtName, "top:60.0px;left:120.0px;");
		
		// txtSurname
		txtSurname = new TextField();
		txtSurname.setImmediate(false);
		txtSurname.setWidth("-1px");
		txtSurname.setHeight("-1px");
		mainLayout.addComponent(txtSurname, "top:100.0px;left:120.0px;");
		
		// txtAddress
		txtAddress = new TextField();
		txtAddress.setImmediate(false);
		txtAddress.setWidth("-1px");
		txtAddress.setHeight("-1px");
		mainLayout.addComponent(txtAddress, "top:140.0px;left:120.0px;");
		
		// txtEmail
		txtEmail = new TextField();
		txtEmail.setImmediate(false);
		txtEmail.setWidth("-1px");
		txtEmail.setHeight("-1px");
		mainLayout.addComponent(txtEmail, "top:180.0px;left:120.0px;");
		
		// btnSearch
		btnSearch = new Button();
		btnSearch.setCaption("Buscar");
		btnSearch.setImmediate(false);
		btnSearch.setWidth("-1px");
		btnSearch.setHeight("-1px");
		mainLayout.addComponent(btnSearch, "top:20.0px;left:280.0px;");
		
		return mainLayout;
	}

	@Override
	public void buttonClick(ClickEvent event) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void enter(ViewChangeEvent event) {
		// TODO Auto-generated method stub
		
	}

}
