package views;

import org.apache.axis2.AxisFault;

import servicelayer.service.ServiceWebStub;
import servicelayer.service.ServiceWebStub.InsertUser;
import servicelayer.service.ServiceWebStub.VOUser;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;
import com.vaadin.ui.TextField;

public class CreateUserView extends CustomComponent implements View {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Label lbl_userType;
	@AutoGenerated
	private CheckBox check_manager;
	@AutoGenerated
	private Button btn_cancel;
	@AutoGenerated
	private CheckBox check_partner;
	@AutoGenerated
	private Button btn_add;
	@AutoGenerated
	private Label label_2;
	@AutoGenerated
	private TextField txt_userName;
	@AutoGenerated
	private TextField txt_email;
	@AutoGenerated
	private TextField txt_createLastName;
	@AutoGenerated
	private TextField txt_name;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public CreateUserView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		btn_add.addClickListener(new Button.ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				ServiceWebStub createUserService;
				
				try{
					createUserService = new ServiceWebStub();					
					
					InsertUser createUser = new InsertUser();
					//Creo el ValueObjet cargandolo con los datos carados por el usuario
					VOUser newUser = new VOUser();
					newUser.setUserName(txt_userName.getValue());
					newUser.setName(txt_name.getValue());
					newUser.setLastName(txt_createLastName.getValue());
					newUser.setEmail(txt_email.getValue());
					if(check_partner.getValue()){
						newUser.setUserType(1);
					} else {
						newUser.setUserType(2);
					}
					//la contrasenia por defecto es el mismo que el nombre de usuario
					newUser.setPassword(txt_userName.getValue());
					createUser.setVoUser(newUser);
					
					if(createUserService.insertUser(createUser).get_return()){
						Notification.show("Aviso: ","Usuario creado correctamente", Notification.TYPE_HUMANIZED_MESSAGE);
					} else {
						Notification.show("Aviso: ","Usuario no creado", Notification.TYPE_ERROR_MESSAGE);
					}
					 
					
				}catch (AxisFault e) {
					e.printStackTrace();
				} catch (java.rmi.RemoteException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}				
			}
		});
		
	}

	@Override
	public void enter(ViewChangeEvent event) {
		// TODO Auto-generated method stub
		
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("360px");
		mainLayout.setHeight("501px");
		
		// top-level component properties
		setWidth("360px");
		setHeight("501px");
		
		// txt_name
		txt_name = new TextField();
		txt_name.setCaption("Nombre");
		txt_name.setImmediate(false);
		txt_name.setWidth("240px");
		txt_name.setHeight("-1px");
		txt_name.setRequired(true);
		mainLayout.addComponent(txt_name, "top:120.0px;left:60.0px;");
		
		// txt_createLastName
		txt_createLastName = new TextField();
		txt_createLastName.setCaption("Apellido");
		txt_createLastName.setImmediate(false);
		txt_createLastName.setWidth("241px");
		txt_createLastName.setHeight("-1px");
		txt_createLastName.setTabIndex(1);
		txt_createLastName.setRequired(true);
		txt_createLastName.setNullSettingAllowed(true);
		mainLayout.addComponent(txt_createLastName, "top:176.0px;left:59.0px;");
		
		// txt_email
		txt_email = new TextField();
		txt_email.setCaption("Email");
		txt_email.setImmediate(false);
		txt_email.setWidth("240px");
		txt_email.setHeight("-1px");
		txt_email.setTabIndex(2);
		txt_email.setRequired(true);
		mainLayout.addComponent(txt_email, "top:236.0px;left:60.0px;");
		
		// txt_userName
		txt_userName = new TextField();
		txt_userName.setCaption("Nombre de usuario");
		txt_userName.setImmediate(false);
		txt_userName.setWidth("240px");
		txt_userName.setHeight("-1px");
		txt_userName.setTabIndex(3);
		txt_userName.setRequired(true);
		mainLayout.addComponent(txt_userName, "top:300.0px;left:60.0px;");
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("Crear usuario");
		mainLayout.addComponent(label_2, "top:62.0px;left:60.0px;");
		
		// btn_add
		btn_add = new Button();
		btn_add.setCaption("Crear");
		btn_add.setImmediate(true);
		btn_add.setWidth("101px");
		btn_add.setHeight("-1px");
		btn_add.setTabIndex(6);
		mainLayout.addComponent(btn_add, "top:434.0px;left:59.0px;");
		
		// check_partner
		check_partner = new CheckBox();
		check_partner.setCaption("Socio");
		check_partner.setImmediate(false);
		check_partner.setWidth("-1px");
		check_partner.setHeight("-1px");
		check_partner.setTabIndex(4);
		mainLayout.addComponent(check_partner, "top:372.0px;left:171.0px;");
		
		// btn_cancel
		btn_cancel = new Button();
		btn_cancel.setCaption("Cancelar");
		btn_cancel.setImmediate(true);
		btn_cancel.setWidth("100px");
		btn_cancel.setHeight("-1px");
		btn_cancel.setTabIndex(7);
		mainLayout.addComponent(btn_cancel, "top:434.0px;left:200.0px;");
		
		// check_manager
		check_manager = new CheckBox();
		check_manager.setCaption("Gerente");
		check_manager.setImmediate(false);
		check_manager.setWidth("-1px");
		check_manager.setHeight("-1px");
		check_manager.setTabIndex(5);
		mainLayout.addComponent(check_manager, "top:344.0px;left:171.0px;");
		
		// lbl_userType
		lbl_userType = new Label();
		lbl_userType.setImmediate(false);
		lbl_userType.setWidth("-1px");
		lbl_userType.setHeight("-1px");
		lbl_userType.setValue("Tipo de usuario:");
		mainLayout.addComponent(lbl_userType, "top:346.0px;left:60.0px;");
		
		return mainLayout;
	}

}
