package views;

import com.example.webvaadin.WebvaadinUI;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.AbsoluteLayout;

import entities.RequestContext;

public class MainMenuView extends BaseView {

	@AutoGenerated
	private AbsoluteLayout mainLayout;

	public MainMenuView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");

		setWidth("-1px");
		setHeight("-1px");
		
		return mainLayout;
	}
	
	@Override
	public void enter(ViewChangeEvent event) {
		if(RequestContext.getRequestContext() == null)
		{
			WebvaadinUI.changeToLogin();
			getUI().getNavigator().navigateTo(WebvaadinUI.LOGINVIEW);
		}
		else
		{
			WebvaadinUI.changeToMainMenu();
			switch(RequestContext.getRequestContext().getUserType()){
			case 1:
				getUI().getNavigator().navigateTo(WebvaadinUI.CATALOGUSERS);
				break;
			case 2:
				getUI().getNavigator().navigateTo(WebvaadinUI.CATALOGEMPLOYEES);
				break;
			default:
				break;
			}
		}
	}

}
