package com.example.webvaadin;

import org.apache.axis2.AxisFault;
import org.openqa.grid.common.exception.RemoteException;

import com.example.service.TestWSStub;
import com.example.service.TestWSStub.GetUserDescriptionFromDB;
import com.example.service.TestWSStub.UserDescription;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Button.ClickEvent;

public class customUserDescription extends CustomComponent implements View, Button.ClickListener {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private AbsoluteLayout absoluteLayout_2;
	@AutoGenerated
	private Button btnSearch;
	@AutoGenerated
	private TextField txtEmail;
	@AutoGenerated
	private TextField txtAddress;
	@AutoGenerated
	private TextField txtSurname;
	@AutoGenerated
	private TextField txtName;
	@AutoGenerated
	private TextField txtId;
	@AutoGenerated
	private Label lblEmail;
	@AutoGenerated
	private Label lblAddress;
	@AutoGenerated
	private Label lblSurname;
	@AutoGenerated
	private Label lblName;
	@AutoGenerated
	private Label lblId;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public customUserDescription() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		
		btnSearch.addClickListener(new Button.ClickListener() {
			
			public void buttonClick(ClickEvent event) {
				// TODO Auto-generated method stub
				
				TestWSStub userDescriptionService;
				
				try {
					userDescriptionService = new TestWSStub();
					
					GetUserDescriptionFromDB getUserDescription = new GetUserDescriptionFromDB();
					getUserDescription.setId(Integer.parseInt(txtId.getValue()));
					UserDescription userDesc = userDescriptionService.getUserDescriptionFromDB(getUserDescription).get_return();
					
					txtId.setValue(String.valueOf(userDesc.getId()));
					txtName.setValue(userDesc.getName());
					txtSurname.setValue(userDesc.getSurname());
					txtAddress.setValue(userDesc.getAddress());
					txtEmail.setValue(userDesc.getEmail());
					
				}catch (AxisFault e) {
					e.printStackTrace();
				} catch (java.rmi.RemoteException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				
			}
		});
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// absoluteLayout_2
		absoluteLayout_2 = buildAbsoluteLayout_2();
		mainLayout.addComponent(absoluteLayout_2,
				"top:60.0px;right:159.0px;bottom:270.0px;left:40.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private AbsoluteLayout buildAbsoluteLayout_2() {
		// common part: create layout
		absoluteLayout_2 = new AbsoluteLayout();
		absoluteLayout_2.setImmediate(false);
		absoluteLayout_2.setWidth("100.0%");
		absoluteLayout_2.setHeight("100.0%");
		
		// lblId
		lblId = new Label();
		lblId.setImmediate(false);
		lblId.setWidth("-1px");
		lblId.setHeight("-1px");
		lblId.setValue("Id");
		absoluteLayout_2.addComponent(lblId, "top:16.0px;left:270.0px;");
		
		// lblName
		lblName = new Label();
		lblName.setImmediate(false);
		lblName.setWidth("-1px");
		lblName.setHeight("-1px");
		lblName.setValue("Nombre");
		absoluteLayout_2.addComponent(lblName, "top:56.0px;left:237.0px;");
		
		// lblSurname
		lblSurname = new Label();
		lblSurname.setImmediate(false);
		lblSurname.setWidth("-1px");
		lblSurname.setHeight("-1px");
		lblSurname.setValue("Apellido");
		absoluteLayout_2.addComponent(lblSurname, "top:100.0px;left:237.0px;");
		
		// lblAddress
		lblAddress = new Label();
		lblAddress.setImmediate(false);
		lblAddress.setWidth("-1px");
		lblAddress.setHeight("-1px");
		lblAddress.setValue("Direccion");
		absoluteLayout_2.addComponent(lblAddress, "top:142.0px;left:230.0px;");
		
		// lblEmail
		lblEmail = new Label();
		lblEmail.setImmediate(false);
		lblEmail.setWidth("-1px");
		lblEmail.setHeight("-1px");
		lblEmail.setValue("Email");
		absoluteLayout_2.addComponent(lblEmail, "top:176.0px;left:250.0px;");
		
		// txtId
		txtId = new TextField();
		txtId.setImmediate(false);
		txtId.setWidth("-1px");
		txtId.setHeight("-1px");
		absoluteLayout_2.addComponent(txtId, "top:16.0px;left:300.0px;");
		
		// txtName
		txtName = new TextField();
		txtName.setImmediate(false);
		txtName.setWidth("-1px");
		txtName.setHeight("-1px");
		absoluteLayout_2.addComponent(txtName, "top:56.0px;left:300.0px;");
		
		// txtSurname
		txtSurname = new TextField();
		txtSurname.setImmediate(false);
		txtSurname.setWidth("-1px");
		txtSurname.setHeight("-1px");
		absoluteLayout_2.addComponent(txtSurname, "top:100.0px;left:299.0px;");
		
		// txtAddress
		txtAddress = new TextField();
		txtAddress.setImmediate(false);
		txtAddress.setWidth("-1px");
		txtAddress.setHeight("-1px");
		absoluteLayout_2.addComponent(txtAddress, "top:136.0px;left:300.0px;");
		
		// txtEmail
		txtEmail = new TextField();
		txtEmail.setImmediate(false);
		txtEmail.setWidth("-1px");
		txtEmail.setHeight("-1px");
		absoluteLayout_2.addComponent(txtEmail, "top:176.0px;left:299.0px;");
		
		// btnSearch
		btnSearch = new Button();
		btnSearch.setCaption("Buscar");
		btnSearch.setImmediate(false);
		btnSearch.setWidth("-1px");
		btnSearch.setHeight("-1px");
		absoluteLayout_2.addComponent(btnSearch, "top:16.0px;left:490.0px;");
		
		return absoluteLayout_2;
	}

	@Override
	public void buttonClick(ClickEvent event) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void enter(ViewChangeEvent event) {
		// TODO Auto-generated method stub
		
	}

}
