CREATE DATABASE  IF NOT EXISTS `meerkatSYS_POC` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `meerkatSYS_POC`;

CREATE TABLE `user` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`UserName` VARCHAR(20) NULL DEFAULT NULL,
	`Password` VARCHAR(20) NULL DEFAULT NULL,
	`Name` VARCHAR(20) NULL DEFAULT NULL,
	`LastName` VARCHAR(20) NULL DEFAULT NULL,
	`Email` VARCHAR(100) NULL DEFAULT NULL,
	PRIMARY KEY (`Id`)
);