package views.liquidation;

import java.util.Collection;
import java.util.Date;

import views.BaseView;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanContainer;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.shared.ui.datefield.Resolution;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Grid;
import com.vaadin.ui.Label;
import com.vaadin.ui.PopupDateField;

import controllers.LiquidationController;
import entities.Bill;
import entities.CompanyLiquidation;
import entities.ProjectLiquidation;
import entities.RequestContext;

public class CatalogLiquidationsView extends BaseView {

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	Label lblTitle;
	PopupDateField dateMonth;
	Grid grdCompanyLiquidation;
	Grid grdProjectLiquidation;
	BeanItemContainer<CompanyLiquidation> beanCompanyLiquidation;
	BeanItemContainer<ProjectLiquidation> beanProjectLiquidation;
	Collection<ProjectLiquidation> projectsLiquidations;
	Collection<CompanyLiquidation> companyliquidations;
	
	

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public CatalogLiquidationsView() {
		super("Liquidaciones", "Catálogo liquidaciones");
		
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private void buildMainLayout() {
		// the main layout and components will be created here
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("540px");

		// top-level component properties
		setWidth("100.0%");
		setHeight("540px");

		// lblTitle
		lblTitle = new Label();
		lblTitle.setStyleName("titleLabel");
		lblTitle.setImmediate(false);
		lblTitle.setWidth("-1px");
		lblTitle.setHeight("-1px");
		lblTitle.setValue(getBreadCrumbToShow());
		mainLayout.addComponent(lblTitle, "top:42.0px;left:0.0px;");
		
		// dateMonth
		dateMonth = new PopupDateField();
		dateMonth.setCaption("Correspondiente al mes");
		dateMonth.setImmediate(true);
		dateMonth.setWidth("250px");
		dateMonth.setHeight("-1px");
		dateMonth.setRequired(true);
		dateMonth.setDateFormat("MM-yyyy");
		dateMonth.setResolution(Resolution.MONTH);
		dateMonth.setValue(new Date());
		dateMonth.setInputPrompt("Seleccione mes a liquidar");
		dateMonth.setDateOutOfRangeMessage("Fecha no válida");
		mainLayout.addComponent(dateMonth, "top:116.0px;left:0.0px;");
		
		
				

	}
	
	private void buildGrids(){
		//grdCompanyLiquidation

		beanCompanyLiquidation = new BeanItemContainer<CompanyLiquidation>(CompanyLiquidation.class,companyliquidations);
		grdCompanyLiquidation = new Grid(beanCompanyLiquidation);
		
		
		
		
		//grdProjectLiquidation
		beanProjectLiquidation = new BeanItemContainer<ProjectLiquidation>(ProjectLiquidation.class,projectsLiquidations);
		grdProjectLiquidation = new Grid(beanProjectLiquidation);
		
		mainLayout.addComponent(grdProjectLiquidation, "top:130.0px;left:0.0px;");
		
	}
	
	@Override
	public void enter(ViewChangeEvent event) {
		super.enter(event);
		if (RequestContext.getRequestContext() != null) {
			LiquidationController.getProjectsLiquidations(dateMonth.getValue());
			buildGrids();
			
		}
	}

}
