package views.bill;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Collection;
import java.util.Date;

import utils.PopupWindow;
import views.BaseView;

import com.example.webvaadin.WebvaadinUI;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.data.util.BeanItem;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.data.util.converter.StringToDoubleConverter;
import com.vaadin.data.util.filter.SimpleStringFilter;
import com.vaadin.event.FieldEvents.TextChangeEvent;
import com.vaadin.event.FieldEvents.TextChangeListener;
import com.vaadin.event.SelectionEvent;
import com.vaadin.event.SelectionEvent.SelectionListener;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.shared.ui.datefield.Resolution;
import com.vaadin.shared.ui.label.ContentMode;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Grid;
import com.vaadin.ui.Grid.HeaderCell;
import com.vaadin.ui.Grid.HeaderRow;
import com.vaadin.ui.Grid.SelectionMode;
import com.vaadin.ui.Label;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;

import controllers.BillController;
import controllers.ChargeController;
import controllers.ProjectController;
import entities.Bill;
import entities.Charge;
import entities.Project;
import entities.RequestContext;

public class UpdateBillView extends BaseView {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private static final long serialVersionUID = 1L;
	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button btnCancel;
	@AutoGenerated
	private Button btnUpdate;
	@AutoGenerated
	private PopupDateField popupDateFieldAppliedDate;
	@AutoGenerated
	private ComboBox comboBoxProjects;
	@AutoGenerated
	private TextField txtTypeExchange;
	@AutoGenerated
	private OptionGroup optionGroupCurrency;
	@AutoGenerated
	private TextField txtAmount;
	@AutoGenerated
	private TextArea txtDescription;
	@AutoGenerated
	private PopupDateField popupDateFieldTo;
	@AutoGenerated
	private PopupDateField popupDateFieldFrom;
	@AutoGenerated
	private Label lblInfo;
	@AutoGenerated
	private Label lblTitle;
	private Grid billsGrid;
	private BeanItemContainer<Bill> beanContainer;
	private Label lblMessage;
	
	@SuppressWarnings("deprecation")
	public UpdateBillView() {
		
		super("Facturas", "Modificar facturas");
		
		buildMainLayout();
		setCompositionRoot(mainLayout);

		builInputs();
		
		lblMessage = new Label("");
		mainLayout.addComponent(lblMessage, "top:183.0px;left:0.0px;");
		
		optionGroupCurrency.addItems("Pesos", "Dolares");
		optionGroupCurrency.select("Pesos");
		
		optionGroupCurrency.addListener(new ValueChangeListener() {
			private static final long serialVersionUID = 1L;

			@Override
       	 	public void valueChange(ValueChangeEvent event) {
       		
	       	 	if(optionGroupCurrency.getValue() == "Dolares")
	   	 			txtTypeExchange.setVisible(true);
	   	 		else
	   	 			txtTypeExchange.setVisible(false);
       	 	}
        });
		
		popupDateFieldFrom.addListener(new ValueChangeListener() {
		    private static final long serialVersionUID = 1L;

			@Override
			public void valueChange(ValueChangeEvent event) {
				buildGrid();
			}
		});
		
		popupDateFieldTo.addListener(new ValueChangeListener() {
		    private static final long serialVersionUID = 1L;

			@Override
			public void valueChange(ValueChangeEvent event) {
				buildGrid(); 
			}
		});
		
		btnUpdate.addClickListener(new Button.ClickListener() {
			private static final long serialVersionUID = 1L;

			@Override
			public void buttonClick(ClickEvent event) {
				btnUpdate.setEnabled(false);
				btnCancel.setEnabled(false);
				txtDescription.setValidationVisible(true);
				txtAmount.setValidationVisible(true);
				comboBoxProjects.setValidationVisible(true);
				txtTypeExchange.setValidationVisible(true);
				
				boolean valid = true;
				
				if(optionGroupCurrency.getValue() == "Dolares" && !txtTypeExchange.isValid())
				{
					txtTypeExchange.setRequiredError("Es requerido");
					valid = false;
				}
				
				if(!txtAmount.isValid() || !txtDescription.isValid() || !popupDateFieldAppliedDate.isValid() || !comboBoxProjects.isValid()){
					txtAmount.setRequiredError("Es requerido");
					txtDescription.setRequiredError("Es requerido");
					txtAmount.setConversionError("Debe ser numérico");
					popupDateFieldAppliedDate.setRequiredError("Es requerido");
					comboBoxProjects.setRequiredError("Es requerido");
					valid = false;
				}
				
				if(valid)
				{
					Bill item = (Bill) billsGrid.getSelectedRow();
					Bill bill = new Bill();
					bill.setCode(item.getCode());
					bill.setDescription(txtDescription.getValue());
					bill.setProjectId(Integer.parseInt(comboBoxProjects.getValue().toString()));
					bill.setAppliedDateTimeUTC(popupDateFieldAppliedDate.getValue());
					bill.setId(item.getId());
					
					if(optionGroupCurrency.getValue() == "Pesos")
					{
						bill.setAmountPeso((Double)(txtAmount.getConvertedValue()));
						bill.setIsCurrencyDollar(false);
					}
					else
					{
						bill.setAmountDollar((Double)(txtAmount.getConvertedValue()));
						bill.setTypeExchange((Double)(txtTypeExchange.getConvertedValue()));
						bill.setIsCurrencyDollar(true);
					}
					
					Bill result = BillController.updateBill(item.getId(), bill);

					if(result != null)
					{
						new PopupWindow("AVISO", "Factura modificada correctamente");
						clearInputs();
						buildGrid();
					}
					else
					{
						btnCancel.setEnabled(true);
						btnUpdate.setEnabled(true);
					}
				}
				else
				{
					btnUpdate.setEnabled(true);
					btnCancel.setEnabled(true);
				}
			}
		
		});
		
		btnCancel.addClickListener(new Button.ClickListener() {
			private static final long serialVersionUID = 1L;

			@Override
			public void buttonClick(ClickEvent event) {
				getUI().getNavigator().navigateTo(WebvaadinUI.MAINMENU);
			}
		});

		
		// TODO add user code here
	}
	
	void clearInputs()
	{
		txtDescription.clear();
		txtAmount.clear();
		txtTypeExchange.clear();
		
		txtDescription.setValidationVisible(false);
		txtAmount.setValidationVisible(false);
		txtTypeExchange.setValidationVisible(false);
		comboBoxProjects.setValidationVisible(false);
		
		popupDateFieldAppliedDate.setValue(new Date());
		
		optionGroupCurrency.select("Pesos");
		
		comboBoxProjects.removeAllItems();
		comboBoxProjects.setValue(0);
		comboBoxProjects.setNullSelectionItemId(null);
		
		txtTypeExchange.setVisible(false);
	}
	
	void builInputs()
	{
		Calendar cal = Calendar.getInstance();
		cal.add(Calendar.MONTH, -1);
		popupDateFieldFrom.setValue(cal.getTime());
		popupDateFieldFrom.setDateFormat("MM-yyyy");
		popupDateFieldFrom.setResolution(Resolution.MONTH);
		
		popupDateFieldTo.setValue(new Date());
		popupDateFieldTo.setDateFormat("MM-yyyy");
		popupDateFieldTo.setResolution(Resolution.MONTH);
		
		clearInputs();
	}
	
	void buildEntityData(Bill bill)
	{
		txtDescription.setValue(bill.getDescription());
		if(bill.getIsCurrencyDollar())
		{
			optionGroupCurrency.select("Dolares");
			txtTypeExchange.setConvertedValue(bill.getTypeExchange());
			txtAmount.setConvertedValue(bill.getAmountDollar());
		}
		else
		{
			optionGroupCurrency.select("Pesos");
			txtAmount.setConvertedValue(bill.getAmountPeso());
		}
		
		comboBoxProjects.setValue(bill.getProjectId());
		comboBoxProjects.setNullSelectionItemId(new Project());
		
		popupDateFieldAppliedDate.setValue(bill.getAppliedDateTimeUTC());
	}
	
	void buildProjects()
	{
		comboBoxProjects.clear();
		comboBoxProjects.removeAllItems();
		
		Collection<Project> projects = ProjectController.getActiveProjects();
		for(Project project : projects)
		{
			comboBoxProjects.addItem(project.getId());
			comboBoxProjects.setItemCaption(project.getId(), project.getName());
		}
	}
	
	public void buildGrid(){
		
		Collection<Bill> bills = BillController.getBillsByFiltersAndActiveProjects(popupDateFieldFrom.getValue(), popupDateFieldTo.getValue(), false, false);
		
		if (bills != null && bills.size() > 0) {
			
			if (billsGrid != null) {
				mainLayout.removeComponent(billsGrid);
			}
			
			lblMessage.setValue("");
			
			beanContainer = new BeanItemContainer<Bill>(Bill.class,bills);
					
			billsGrid = new Grid(beanContainer);
			billsGrid.removeColumn("id");
			billsGrid.removeColumn("projectId");
			billsGrid.removeColumn("appliedDateTimeUTC");
			billsGrid.removeColumn("amountPeso");
			billsGrid.removeColumn("amountDollar");
			billsGrid.removeColumn("isCurrencyDollar");
			billsGrid.removeColumn("typeExchange");
			billsGrid.removeColumn("typeExchangeToShow");
			billsGrid.removeColumn("appliedDateTimeUTCToShow");
			billsGrid.removeColumn("projectName");
			billsGrid.setColumnOrder("code", "description", "amountToShow", "amountChargedToShow");
	
			billsGrid.getColumn("code").setHeaderCaption("Código");
			billsGrid.getColumn("description").setHeaderCaption("Descripción");
			billsGrid.getColumn("amountToShow").setHeaderCaption("Monto");
			billsGrid.getColumn("amountChargedToShow").setHeaderCaption("Monto cobrado");
			billsGrid.setWidth(620, Unit.PIXELS);
			billsGrid.setHeight(285, Unit.PIXELS);
			billsGrid.setSelectionMode(SelectionMode.SINGLE);
			billsGrid.getSelectedRows().clear();
			//billsGrid.select(bills.iterator().next());
			//buildEntityData(bills.iterator().next());
			
			HeaderRow filterRow = billsGrid.appendHeaderRow();
			for ( final Object pid: billsGrid.getContainerDataSource().getContainerPropertyIds()){
				HeaderCell cell = filterRow.getCell(pid);
				if(cell != null){
					TextField txtFilter = new TextField();
					txtFilter.setImmediate(true);
					txtFilter.setWidth("125px");
					txtFilter.setHeight("30px");
					txtFilter.setInputPrompt("Filtro");
					
					txtFilter.addTextChangeListener(new TextChangeListener() {	 
						private static final long serialVersionUID = 1L;

					@Override
					  public void textChange(TextChangeEvent event) {
					   String newValue = (String) event.getText();
					  
					   @SuppressWarnings("unchecked")
					   BeanItemContainer<Bill> container = ((BeanItemContainer<Bill>) billsGrid.getContainerDataSource());
					  
					   container.removeContainerFilters(pid);
					   if (null != newValue && !newValue.isEmpty()) {
						   container.addContainerFilter(new SimpleStringFilter(pid, newValue, true, false));
					   }					   
					  }	
					 });
					cell.setComponent(txtFilter);	
				}
			}
			
			mainLayout.addComponent(billsGrid, "top:35%;left:0px;");
			
			billsGrid.addSelectionListener(new SelectionListener() {
				private static final long serialVersionUID = 1L;

				@Override
				public void select(SelectionEvent event) {
					
					BeanItem<Bill> item = beanContainer.getItem(billsGrid.getSelectedRow());
					if(item != null){
						Bill selectedBill = item.getBean();						
						
						setEnabledEditionInputs(true);
						setRequiredEditionInputs(true);
						buildProjects();
						buildEntityData(selectedBill);
					}
					else
					{
						setEnabledEditionInputs(false);
						setRequiredEditionInputs(false);
						clearInputs();
					}
				}
				
			});
			
			setVisibleEditionInputs(true);
			setEnabledEditionInputs(false);
			setRequiredEditionInputs(false);
		}
		else
		{
			if(billsGrid != null)
			{
				billsGrid.setVisible(false);
			}
			
			String strDateFrom = new SimpleDateFormat("MM-yyyy").format(popupDateFieldFrom.getValue());
			String strDateTo = new SimpleDateFormat("MM-yyyy").format(popupDateFieldTo.getValue());

			lblMessage.setValue("No hay facturas para mostrar entre el rango fechas " + strDateFrom  + " - " + strDateTo);
			
			setVisibleEditionInputs(false);
		}
	}
	
	void setEnabledEditionInputs(boolean enabled)
	{
		btnUpdate.setEnabled(enabled);
		btnCancel.setEnabled(enabled);
		txtDescription.setEnabled(enabled);
		optionGroupCurrency.setEnabled(enabled);
		txtAmount.setEnabled(enabled);
		comboBoxProjects.setEnabled(enabled);
		popupDateFieldAppliedDate.setEnabled(enabled);
	}
	
	void setRequiredEditionInputs(boolean required)
	{
		txtDescription.setRequired(required);
		txtAmount.setRequired(required);
		optionGroupCurrency.setRequired(required);
		txtAmount.setRequired(required);
		comboBoxProjects.setRequired(required);
		popupDateFieldAppliedDate.setRequired(required);
	}
	
	void setVisibleEditionInputs(boolean visible)
	{
		btnUpdate.setVisible(visible);
		btnCancel.setVisible(visible);
		txtDescription.setVisible(visible);
		optionGroupCurrency.setVisible(visible);
		txtAmount.setVisible(visible);
		comboBoxProjects.setVisible(visible);
		popupDateFieldAppliedDate.setVisible(visible);
	}
	
	@Override
	public void enter(ViewChangeEvent event) {
		super.enter(event);
		if(RequestContext.getRequestContext() != null){
			// Compruebo si el usuario es de tipo socio
			if(RequestContext.getRequestContext().getUserType() != 2){
				getUI().getNavigator().navigateTo(WebvaadinUI.MAINMENU);
			}
			
			builInputs();
			buildGrid();
		}
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("880px");
		mainLayout.setHeight("501px");
		
		// top-level component properties
		setWidth("880px");
		setHeight("800px");
		
		// lblTitle
		lblTitle = new Label();
		lblTitle.setStyleName("titleLabel");
		lblTitle.setImmediate(false);
		lblTitle.setWidth("-1px");
		lblTitle.setHeight("-1px");
		lblTitle.setValue(getBreadCrumbToShow());
		mainLayout.addComponent(lblTitle, "top:40.0px;left:0.0px;");
		
		// lblInfo
		lblInfo = new Label();
		lblInfo.setStyleName("update-bill-lblInformation");
		lblInfo.setContentMode(ContentMode.HTML);
		lblInfo.setImmediate(false);
		lblInfo.setWidth("-1px");
		lblInfo.setHeight("-1px");
		StringBuilder strBuilder = new StringBuilder();
		strBuilder.append("<b>Importante:</b> Las facturas que se muestran cumplen con lo siguiente</br>");
		strBuilder.append("- No estan liquidadas aun</br>");
		strBuilder.append("- No tienen cobros asociados</br>");
		strBuilder.append("- Pertenecen a proyectos activos");
		lblInfo.setValue(strBuilder.toString());
		mainLayout.addComponent(lblInfo, "top:100.0px;left:270.0px;");
		
		// popupDateFieldFrom
		popupDateFieldFrom = new PopupDateField();
		popupDateFieldFrom.setCaption("Desde");
		popupDateFieldFrom.setImmediate(true);
		popupDateFieldFrom.setWidth("120px");
		popupDateFieldFrom.setHeight("-1px");
		popupDateFieldFrom.setTabIndex(1);
		popupDateFieldFrom.setRequired(true);
		mainLayout.addComponent(popupDateFieldFrom, "top:120.0px;left:0.0px;");
		
		// popupDateFieldTo
		popupDateFieldTo = new PopupDateField();
		popupDateFieldTo.setCaption("Hasta");
		popupDateFieldTo.setImmediate(true);
		popupDateFieldTo.setWidth("120px");
		popupDateFieldTo.setHeight("-1px");
		popupDateFieldTo.setTabIndex(2);
		popupDateFieldTo.setRequired(true);
		mainLayout.addComponent(popupDateFieldTo, "top:120.0px;left:140.0px;");
		
		// txtDescription
		txtDescription = new TextArea();
		txtDescription.setCaption("Descripción");
		txtDescription.setImmediate(true);
		txtDescription.setWidth("250px");
		txtDescription.setHeight("-1px");
		txtDescription.setMaxLength(240);
		txtDescription.setRows(1);
		txtDescription.setTabIndex(4);
		txtDescription.setNullRepresentation("");
		txtDescription.setTabIndex(3);
		txtDescription.setRequired(true);
		mainLayout.addComponent(txtDescription, "top:190.0px;right:0px;");
		
		// txtAmount
		txtAmount = new TextField();
		txtAmount.setCaption("Importe");
		txtAmount.setImmediate(true);
		txtAmount.setWidth("120px");
		txtAmount.setHeight("-1px");
		txtAmount.setTabIndex(5);
		txtAmount.setRequired(true);
		txtAmount.setNullRepresentation("");
		txtAmount.setConverter(new StringToDoubleConverter());
		mainLayout.addComponent(txtAmount, "top:330.0px;left:630.0px;");
		
		// optionGroupCurrency
		optionGroupCurrency = new OptionGroup();
		optionGroupCurrency.setCaption("Moneda");
		optionGroupCurrency.setImmediate(true);
		optionGroupCurrency.setWidth("-1px");
		optionGroupCurrency.setHeight("-1px");
		optionGroupCurrency.setTabIndex(4);
		mainLayout.addComponent(optionGroupCurrency,
				"top:250.0px;left:630.0px;");
		
		// txtTypeExchange
		txtTypeExchange = new TextField();
		txtTypeExchange.setCaption("Tipo de cambio");
		txtTypeExchange.setImmediate(true);
		txtTypeExchange.setVisible(false);
		txtTypeExchange.setWidth("120px");
		txtTypeExchange.setHeight("-1px");
		txtTypeExchange.setTabIndex(6);
		txtTypeExchange.setRequired(true);
		txtTypeExchange.setNullRepresentation("");
		txtTypeExchange.setConverter(new StringToDoubleConverter());
		mainLayout.addComponent(txtTypeExchange, "top:330.0px;right:0px;");
		
		// comboBoxProjects
		comboBoxProjects = new ComboBox();
		comboBoxProjects.setCaption("Proyecto");
		comboBoxProjects.setImmediate(true);
		comboBoxProjects.setWidth("250px");
		comboBoxProjects.setHeight("-1px");
		comboBoxProjects.setTabIndex(7);
		comboBoxProjects.setRequired(true);
		mainLayout.addComponent(comboBoxProjects, "top:385.0px;right:0px;");
		
		// popupDateFieldAppliedDate
		popupDateFieldAppliedDate = new PopupDateField();
		popupDateFieldAppliedDate.setCaption("Mes");
		popupDateFieldAppliedDate.setImmediate(false);
		popupDateFieldAppliedDate.setWidth("-1px");
		popupDateFieldAppliedDate.setHeight("-1px");
		popupDateFieldAppliedDate.setTabIndex(8);
		popupDateFieldAppliedDate.setRequired(true);
		popupDateFieldAppliedDate.setDateFormat("MM-yyyy");
		popupDateFieldAppliedDate.setValue(new Date());
		popupDateFieldAppliedDate.setResolution(Resolution.MONTH);
		mainLayout.addComponent(popupDateFieldAppliedDate,
				"top:450.0px;left:630.0px;");
		
		// btnUpdate
		btnUpdate = new Button();
		btnUpdate.setCaption("Modificar");
		btnUpdate.setImmediate(false);
		btnUpdate.setWidth("120px");
		btnUpdate.setHeight("-1px");
		btnUpdate.setTabIndex(9);
		mainLayout.addComponent(btnUpdate, "top:464.0px;left:0px;");
		
		// btnCancel
		btnCancel = new Button();
		btnCancel.setCaption("Cancelar");
		btnCancel.setImmediate(false);
		btnCancel.setWidth("120px");
		btnCancel.setHeight("-1px");
		btnCancel.setTabIndex(10);
		mainLayout.addComponent(btnCancel, "top:464.0px;left:130.0px;");
		
		return mainLayout;
	}

}
