package views.reports;

import java.lang.reflect.Array;
import java.util.Calendar;
import java.util.Collection;
import java.util.HashMap;

import org.dussan.vaadin.dcharts.DCharts;
import org.dussan.vaadin.dcharts.base.elements.XYaxis;
import org.dussan.vaadin.dcharts.base.elements.XYseries;
import org.dussan.vaadin.dcharts.data.DataSeries;
import org.dussan.vaadin.dcharts.data.Ticks;
import org.dussan.vaadin.dcharts.metadata.LegendPlacements;
import org.dussan.vaadin.dcharts.metadata.SeriesToggles;
import org.dussan.vaadin.dcharts.metadata.TooltipAxes;
import org.dussan.vaadin.dcharts.metadata.XYaxes;
import org.dussan.vaadin.dcharts.metadata.locations.TooltipLocations;
import org.dussan.vaadin.dcharts.metadata.renderers.AxisRenderers;
import org.dussan.vaadin.dcharts.metadata.renderers.SeriesRenderers;
import org.dussan.vaadin.dcharts.options.Axes;
import org.dussan.vaadin.dcharts.options.Highlighter;
import org.dussan.vaadin.dcharts.options.Legend;
import org.dussan.vaadin.dcharts.options.Options;
import org.dussan.vaadin.dcharts.options.Series;
import org.dussan.vaadin.dcharts.options.SeriesDefaults;
import org.dussan.vaadin.dcharts.renderers.legend.EnhancedLegendRenderer;
import org.dussan.vaadin.dcharts.renderers.tick.AxisTickRenderer;
import org.openqa.selenium.internal.BuildInfo;

import views.BaseView;

import com.sun.org.apache.xalan.internal.xsltc.runtime.Hashtable;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.shared.ui.datefield.Resolution;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Label;
import com.vaadin.ui.PopupDateField;

import controllers.BillController;
import controllers.LiquidationController;
import controllers.ProjectController;
import entities.Bill;
import entities.Project;
import entities.ProjectLiquidation;
import entities.ReportAmountCharged;
import entities.RequestContext;

public class ReportProjectDetailsAmountChargedView extends BaseView {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@AutoGenerated
	private AbsoluteLayout mainLayout;
	private PopupDateField popupDateFieldYear;
	private Label lblTitle;
	private ComboBox cboxProject;
	private DCharts chart;
	private Collection<Project> projects;
	private Label lblMessage;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public ReportProjectDetailsAmountChargedView() {
		
		super("Reportes", "Importes a cobrar");
		
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		lblMessage = new Label("");
		mainLayout.addComponent(lblMessage, "top:155.0px;left:0.0px;");
		
		cboxProject.addValueChangeListener(new ValueChangeListener() {

			@Override
			public void valueChange(ValueChangeEvent event) {
				if (cboxProject.getValue() != null && popupDateFieldYear.getValue() != null) {
					int id = (int) cboxProject.getValue();
					
					Project project = getProjectById(id);
					if(project.getIsCurrencyDollar())
						buildChartDollar(id);
					else
						
						buildChartPeso(id);
				}
			}
		});
		
		popupDateFieldYear.addValueChangeListener(new ValueChangeListener() {

			@Override
			public void valueChange(ValueChangeEvent event) {
				if (cboxProject.getValue() != null && popupDateFieldYear.getValue() != null) {
					int id = (int) cboxProject.getValue();
					
					Project project = getProjectById(id);
					if(project.getIsCurrencyDollar())
						buildChartDollar(id);
					else
						
						buildChartPeso(id);
				}
			}
		});
		
		// TODO add user code here
	}
	
	void buildInputs()
	{
		Calendar cal = Calendar.getInstance();
		cal.set(Calendar.DAY_OF_YEAR, 1);
		popupDateFieldYear.setValue(cal.getTime());
		popupDateFieldYear.setDateFormat("yyyy");
		popupDateFieldYear.setResolution(Resolution.YEAR);
		
		if (chart != null) {
			mainLayout.removeComponent(chart);
		}
	}
	
	DCharts buildChart(Collection<Bill> bills, String currency)
	{
		DataSeries dataSeries = new DataSeries();
		
		Bill[] array = (Bill[]) Array.newInstance(Bill.class, bills.size());
		bills.toArray(array);
		
		HashMap<Integer, ReportAmountCharged> projectLiquidationsByMonth = buildReport(array);
		
		dataSeries.add(projectLiquidationsByMonth.get(0).getTotalAmount(), 
					   projectLiquidationsByMonth.get(1).getTotalAmount(), 
					   projectLiquidationsByMonth.get(2).getTotalAmount(),
					   projectLiquidationsByMonth.get(3).getTotalAmount(),
					   projectLiquidationsByMonth.get(4).getTotalAmount(),
					   projectLiquidationsByMonth.get(5).getTotalAmount(),
					   projectLiquidationsByMonth.get(6).getTotalAmount(),
					   projectLiquidationsByMonth.get(7).getTotalAmount(),
					   projectLiquidationsByMonth.get(8).getTotalAmount(),
					   projectLiquidationsByMonth.get(9).getTotalAmount(),
					   projectLiquidationsByMonth.get(10).getTotalAmount(),
					   projectLiquidationsByMonth.get(11).getTotalAmount());
		
		dataSeries.add(projectLiquidationsByMonth.get(0).getAmountCharged(), 
					   projectLiquidationsByMonth.get(1).getAmountCharged(), 
					   projectLiquidationsByMonth.get(2).getAmountCharged(),
					   projectLiquidationsByMonth.get(3).getAmountCharged(),
					   projectLiquidationsByMonth.get(4).getAmountCharged(),
					   projectLiquidationsByMonth.get(5).getAmountCharged(),
					   projectLiquidationsByMonth.get(6).getAmountCharged(),
					   projectLiquidationsByMonth.get(7).getAmountCharged(),
					   projectLiquidationsByMonth.get(8).getAmountCharged(),
					   projectLiquidationsByMonth.get(9).getAmountCharged(),
					   projectLiquidationsByMonth.get(10).getAmountCharged(),
					   projectLiquidationsByMonth.get(11).getAmountCharged());
		
		dataSeries.add(projectLiquidationsByMonth.get(0).getAmountReceivable(), 
					   projectLiquidationsByMonth.get(1).getAmountReceivable(), 
					   projectLiquidationsByMonth.get(2).getAmountReceivable(),
					   projectLiquidationsByMonth.get(3).getAmountReceivable(),
					   projectLiquidationsByMonth.get(4).getAmountReceivable(),
					   projectLiquidationsByMonth.get(5).getAmountReceivable(),
					   projectLiquidationsByMonth.get(6).getAmountReceivable(),
					   projectLiquidationsByMonth.get(7).getAmountReceivable(),
					   projectLiquidationsByMonth.get(8).getAmountReceivable(),
					   projectLiquidationsByMonth.get(9).getAmountReceivable(),
					   projectLiquidationsByMonth.get(10).getAmountReceivable(),
					   projectLiquidationsByMonth.get(11).getAmountReceivable());
		
		SeriesDefaults seriesDefaults = new SeriesDefaults()
			.setFillToZero(true)
			.setRenderer(SeriesRenderers.BAR);

		Series series = new Series()
			.addSeries(
				new XYseries()
					.setLabel("Total facturación IVA incl. "))
		.addSeries(
				new XYseries()
					.setLabel("Total importe cobrado"))
		.addSeries(
				new XYseries()
					.setLabel("Total importe a cobrar"));
		
		Legend legend = new Legend()
			.setShow(true)
			.setRendererOptions(
				new EnhancedLegendRenderer()
					.setSeriesToggle(SeriesToggles.SLOW)
					.setSeriesToggleReplot(true))
			.setPlacement(LegendPlacements.OUTSIDE_GRID);

		Highlighter highlighter = new Highlighter()
			.setShow(true)
			.setShowTooltip(true)
			.setTooltipAlwaysVisible(true)
			.setKeepTooltipInsideChart(true)
			.setTooltipLocation(TooltipLocations.NORTH)
			.setTooltipAxes(TooltipAxes.XY_BAR);
		
		Axes axes = new Axes()
			.addAxis(
				new XYaxis()
					.setRenderer(AxisRenderers.CATEGORY)
					.setTicks(
		                new Ticks()
		                    .add("Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Set", "Oct", "Nov", "Dic")))
			.addAxis(
				new XYaxis(XYaxes.Y)
					.setPad(1.05f)
					.setTickOptions(
						new AxisTickRenderer()
							.setFormatString(currency + " %d")));

		Options options = new Options()
			.setSeriesDefaults(seriesDefaults)
			.setSeries(series)
			.setLegend(legend)
			.setHighlighter(highlighter)
			.setAxes(axes);

		return new DCharts()
			.setDataSeries(dataSeries)
			.setOptions(options)
			.show();
	}
	
	public void buildChartPeso(int projectId){

		if (chart != null) {
			mainLayout.removeComponent(chart);
		}
		
		//Chart pesos
		Collection<Bill> bills =  BillController.getAllBillsByYearAndProject(popupDateFieldYear.getValue(), projectId);
		
		if(bills.size() > 0)
		{	
			lblMessage.setValue("");
			
			chart = buildChart(bills, "$");
			
			chart.setWidth(100, Unit.PERCENTAGE);
			chart.setHeight(350, Unit.PIXELS);
			
			mainLayout.addComponent(chart, "top:19%;left:0px;");
		}
		else
		{
			lblMessage.setValue("No hay datos en el año seleccionado para ese proyecto");
		}
	}
	
	void buildChartDollar(int projectId){
		
		if (chart != null) {
			mainLayout.removeComponent(chart);
		}
		
		//Chart dolares
		Collection<Bill> bills =  BillController.getAllBillsByYearAndProject(popupDateFieldYear.getValue(), projectId);
								
		if(bills.size() > 0)
		{	
			lblMessage.setValue("");
			
			chart = buildChart(bills, "U$S");
			
			chart.setWidth(100, Unit.PERCENTAGE);
			chart.setHeight(350, Unit.PIXELS);
			
			mainLayout.addComponent(chart, "top:19%;left:0px;");
		}
		else 
		{
			lblMessage.setValue("No hay datos en el año seleccionado para ese proyecto");
		}
	}

	HashMap<Integer, ReportAmountCharged> buildReport(Bill[] bills)
	{
		HashMap<Integer, ReportAmountCharged> reportByMonth = new HashMap<Integer, ReportAmountCharged>();
		reportByMonth.put(0, new ReportAmountCharged());
		reportByMonth.put(1, new ReportAmountCharged());
		reportByMonth.put(2, new ReportAmountCharged());
		reportByMonth.put(3, new ReportAmountCharged());
		reportByMonth.put(4, new ReportAmountCharged());
		reportByMonth.put(5, new ReportAmountCharged());
		reportByMonth.put(6, new ReportAmountCharged());
		reportByMonth.put(7, new ReportAmountCharged());
		reportByMonth.put(8, new ReportAmountCharged());
		reportByMonth.put(9, new ReportAmountCharged());
		reportByMonth.put(10, new ReportAmountCharged());
		reportByMonth.put(11, new ReportAmountCharged());
		
		for(int i = 0; i< bills.length; i++)
		{
			int month = bills[i].getAppliedDateTimeUTC().getMonth();
			
			ReportAmountCharged aux = reportByMonth.get(month);
			double amountCharged = aux.getAmountCharged() + bills[i].getAmountCharged();
			double totalAmount = aux.getTotalAmount() + bills[i].getTotalAmount();
			double receivable = aux.getAmountReceivable() + bills[i].getAmountReceivable();
			reportByMonth.put(month, new ReportAmountCharged(totalAmount, amountCharged, receivable));
		}

		return reportByMonth;
	}

	Project getProjectById(int id)
	{
		for(Project p : projects)
		{
			if(p.getId() == id)
			{
				return p;
			}
		}
		return null;
	}
	
	@Override
	public void enter(ViewChangeEvent event) {
		super.enter(event);
		if(RequestContext.getRequestContext() != null){
			projects = ProjectController.getActiveProjects();
			cboxProject.removeAllItems();
			for(Project project : projects)
			{
				cboxProject.addItem(project.getId());
				cboxProject.setItemCaption(project.getId(), project.getName());
			}
			
			buildInputs();
		}
	}
	
	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("880px");
		mainLayout.setHeight("880px");
		
		// top-level component properties
		setWidth("880px");
		setHeight("880px");

		// lblTitle
		lblTitle = new Label();
		lblTitle.setStyleName("titleLabel");
		lblTitle.setImmediate(false);
		lblTitle.setWidth("-1px");
		lblTitle.setHeight("-1px");
		lblTitle.setValue(getBreadCrumbToShow());
		mainLayout.addComponent(lblTitle, "top:40.0px;left:0.0px;");
				
		// popupDateFieldFrom
		popupDateFieldYear = new PopupDateField();
		popupDateFieldYear.setCaption("Año");
		popupDateFieldYear.setImmediate(true);
		popupDateFieldYear.setWidth("105px");
		popupDateFieldYear.setHeight("-1px");
		popupDateFieldYear.setTabIndex(1);
		popupDateFieldYear.setRequired(true);
		mainLayout.addComponent(popupDateFieldYear, "top:105.0px;left:0.0px;");
		
		// cboxProject
		cboxProject = new ComboBox();
		cboxProject.setCaption("Proyecto");
		cboxProject.setImmediate(true);
		cboxProject.setWidth("245px");
		cboxProject.setHeight("-1px");
		cboxProject.setRequired(true);
		cboxProject.setInputPrompt("Seleccione el proyecto");
		cboxProject.setTabIndex(3);
		mainLayout.addComponent(cboxProject, "top:105.0px;left:120.0px;");

		return mainLayout;
	}

}
